<a href="https://colab.research.google.com/github/AI-asma/Bootcamp-Fintech/blob/main/assignment_w5_c1_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Week 5, Assignment C1:

Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

In [3]:
#Objective 1.
#Use this cell to import the Numpy (as np), Pandas (as pd), and YFinance (as yf) packages.

import numpy as np
import pandas as pd
import yfinance as yf 
import pandas_datareader as pdr


In [4]:
#pip install yfinance

In [5]:
#Our work will also require some components of the Sklearn and Pandas_Datareader packages as imported below:

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()

In [6]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".

stock_symbol = "NIO"

In [7]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.

df = pdr.get_data_yahoo(stock_symbol, "2016-1-1", "2021-1-1")
df = df.dropna()
df = df[["Open", "High", "Low", "Close"]]
df

[*********************100%***********************]  1 of 1 completed


Open       High        Low      Close
Date                                                  
2018-09-12   6.000000   6.930000   5.350000   6.600000
2018-09-13   6.620000  12.690000   6.520000  11.600000
2018-09-14  12.660000  13.800000   9.220000   9.900000
2018-09-17   9.610000   9.750000   8.500000   8.500000
2018-09-18   8.730000   9.100000   7.670000   7.680000
...               ...        ...        ...        ...
2020-12-24  46.880001  47.130001  45.349998  45.770000
2020-12-28  46.669998  46.849998  43.669998  44.060001
2020-12-29  43.700001  46.279999  42.230000  46.139999
2020-12-30  46.500000  48.380001  45.720001  48.380001
2020-12-31  48.459999  50.500000  47.770000  48.740002

[581 rows x 4 columns]

In [8]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df["Close"].rolling(window=15).mean()
df['Open_1_Change'] = df["Open"].diff()
df = df.dropna()
X = df[["Close_15_Rolling", "Open_1_Change"]]
X

Close_15_Rolling  Open_1_Change
Date                                       
2018-10-02          7.974667      -0.460000
2018-10-03          7.954667      -0.480000
2018-10-04          7.598000       0.070000
2018-10-05          7.355333       0.010000
2018-10-08          7.191333      -0.130000
...                      ...            ...
2020-12-24         45.140000      -0.599998
2020-12-28         45.208000      -0.210003
2020-12-29         45.276667      -2.969997
2020-12-30         45.398000       2.799999
2020-12-31         45.713334       1.959999

[567 rows x 2 columns]

In [9]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.
y = np.where(-df["Close"].diff(-1) > 0, 1, -1)
y

array([ 1, -1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,
       -1,  1, -1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1, -1,
       -1,  1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1,  1,
       -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1,  1,
        1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1,  1,
       -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1, -1, -1,
        1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
       -1,  1,  1, -1,  1,  1, -1, -1,  1,  1, -1, -1, -1,  1, -1, -1,  1,
        1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1,  1,
       -1, -1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,
        1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1, -1,  1,
       -1, -1,  1, -1, -1, -1,  1,  1,  1, -1, -1,  1, -1, -1,  1,  1,  1,
       -1, -1, -1, -1,  1

In [10]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

index = int(0.7*len(X))
X_train, X_test, y_train, y_test = X[:index], X[index:], y[:index], y[index:]

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(396, 2) (396,) (171, 2) (171,)


In [11]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.

logistic = LogisticRegression()
logistic = logistic.fit(X_train,y_train)

In [12]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame(zip(X.columns, np.transpose(logistic.coef_)))

0                       1
0  Close_15_Rolling  [-0.03597887062954358]
1     Open_1_Change     [0.166878819873887]

In [13]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test)
predictions = logistic.predict(X_test)



In [14]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.

metrics.confusion_matrix(y_test, predictions)

array([[68,  6],
       [94,  3]])

In [15]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.

logistic.score(X_test, y_test)

0.4152046783625731

In [16]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

cross_val = cross_val_score(LogisticRegression() ,X_test, y_test)
cross_val

array([0.57142857, 0.55882353, 0.55882353, 0.44117647, 0.47058824])